### ISSUE TITLE
The BuildsByRepositoryOption don't have branch.name

### ISSUE THREAD

**Issue by miekg** [shuheiktgw/go-travis#1]
Hi thanks, for this useful package, I ran however into a small snag:

According to the docs: https://developer.travis-ci.com/resource/builds#Builds
this endpoint also allows filtering on the branch being pushed, but the current BuildsByRepositoryOption
https://github.com/shuheiktgw/go-travis/blob/master/builds.go#L105, don't support branch.name.

Thanks for any insights.

**Comment by shuheiktgw** [comment]
Hi @miekg, thank you for reporting the issue! 😄 

I think I did not add the `branch.name` option since the option did not seem to work correctly when I implemented it. However, now I figured out what the problem is and fixed it by https://github.com/shuheiktgw/go-travis/pull/4.

The problem is even though the [API doc](https://developer.travis-ci.com/resource/builds#find) suggests `branch.name` is a list of string, [the actual implementation of their API](https://github.com/shuheiktgw/travis-api/blob/f245cccebd4d57bbb45cc3e4fd68de5aff30fc2c/spec/v3/services/builds/find_spec.rb#L391) handles it as a string.

Now I added `BranchName` option `BuildsByRepositoryOption` so you can use it to filter builds. Also, I will create a PR to the original API to fix it to accept a list of branch names since I think that is what most people want.

**Comment by shuheiktgw** [comment]
Now I released v0.1.1 so please use it to use the option! 👍

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [shuheiktgw/go-travis] The Buil..." ]
>Now I released v0.1.1 so please use it to use the option! 👍

Thank you!

**Comment by shuheiktgw** [comment]
Hi, I tried fixing the problem above and realized I misunderstood the problem! I fixed it now and you can specify the array of branchNames! 👍 

So please use v0.1.3 or above and sorry for the inconvenience...
